-- Optional hardening/management patch for the final website.
-- Lets the single Admin pre-approve Manager/Data Entry emails without exposing a service key.

create table if not exists public.role_invites (
  id bigint generated by default as identity primary key,
  email text unique not null,
  role text not null check (role in ('manager','data_entry')),
  active boolean not null default true,
  created_by uuid not null references auth.users(id),
  created_at timestamptz not null default now()
);

alter table public.role_invites enable row level security;

drop policy if exists "Admins can manage role invites" on public.role_invites;
create policy "Admins can manage role invites"
on public.role_invites for all to authenticated
using (public.current_user_role() = 'admin')
with check (public.current_user_role() = 'admin');

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  invited_role text;
begin
  select role into invited_role
  from public.role_invites
  where lower(email) = lower(new.email)
    and active = true
  limit 1;

  insert into public.profiles (id, display_name, role, active)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'display_name', split_part(new.email,'@',1)),
    coalesce(invited_role,'visitor'),
    true
  )
  on conflict (id) do update set
    display_name = excluded.display_name,
    role = excluded.role,
    active = true;

  if invited_role is not null then
    update public.role_invites set active = false where lower(email) = lower(new.email);
  end if;
  return new;
end;
$$;

-- Recreate the existing trigger safely.
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();
